DROP TABLE IF EXISTS sentMessages;

CREATE TABLE SentMessage (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  message VARCHAR(500) NOT NULL,
  timestamp VARCHAR(200) NOT NULL,
  timeToSend DOUBLE NOT NULL
);

